plugins:
  shared_edits_enabled:
    default: true
    client: true
  shared_edits_editor_mode:
    default: "markdown"
    client: true
    type: enum
    choices:
      - markdown
      - rich
  shared_edits_commit_delay_seconds:
    default: 30
    min: 5
    max: 300
  shared_edits_toggle_allowed_groups:
    default: "1|2|14" # @admins, @moderators, @trust_level_4
    type: group_list
    list_type: compact
    allow_any: false
    disallowed_groups: "4" # @anonymous_users
    refresh: true
    mandatory_values: "1" # @admins
